title: Friddle的碎碎念
email: friddle@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  从Ghost回到jenklly.完全是因为不想备案。直接挂在了github上。恩为了解决一个坑。到另一个坑去。
twitter_username: friddle
github_username: friddle
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: CN

include:
 - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-gist
 - jekyll-feed
 - jemoji
 - jekyll-include-cache

author:
 name   : "Friddle Copper"
 avatar : "/assets/images/friddle-avatar.jpg"
 bio    : "The day"
 links:
  - label: "Website"
    icon: "fas fa-fw fa-link"
    url: "https://blog.friddle.me"
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/friddeleo"
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/friddle"
  - label: "Weibo"
    icon: "fab fa-fw fa-weibo"
    url: "https://weibo.com/1593952090"
  - label: "Matters(politics)"
    icon: "fab fa-fw fa-weibo"
    url: "https://matters.news/@friddle"

footer:
 links:
   - label: "weibo"
     icon: "fab fa-fw fa-weibo"
     url: "https://weibo.com/1593952090"

defaults:
 # _posts
 - scope:
    path: ""
    type: posts
   values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
 # _pages
 - scope:
    path: "_pages"
    type: pages
   values:
    layout: single
    author_profile: true

category_archive:
 type: liquid
 path: /categories/

tag_archive:
 type: liquid
 path: /tags/

comments:
   provider: "disqus"
   disqus:
     shortname: "blog.friddle.me"

